refactor
keep-starknet-strange/tsubasa pull request #29
Opened 2023-08-08 15:29 UTC by rkdud007

#28 

- about the test, right now i would suggest we make each unit test per each system, and later if contracts become too complicated, make tests.cairo or test folder for integration : reference : https://github.com/rkdud007/chess-dojo/blob/main/src/tests.cairo

2023-08-08 16:35 UTC, rkdud007 commented
I dont think 'request for review' button is active :/ @LucasLvy could you review this ?

2023-08-08 19:47 UTC, LucasLvy requested changes

2023-08-08 19:47 UTC, LucasLvy commented on contracts/src/systems/place_card.cairo
> +    use tsubasa::components::{Card};
```suggestion
    use tsubasa::components::Card;
```

2023-08-09 02:42 UTC, rkdud007 commented on contracts/src/systems/place_card.cairo
> +    use tsubasa::components::{Card};
updated

2023-08-09 07:29 UTC, LucasLvy approved these changes
Lgtm

2023-08-09 08:26 UTC, rkdud007 commented
@LucasLvy we need to have latest nightly version for CI, currently I have CI issue for print trait, which latest dojo solve it, and because of CI issue cannot merge it :) ( checked sozo test is working ) , suggest maybe we can merge without CI approval so this time and fix it other issue?

2023-08-09 10:23 UTC, LucasLvy requested changes
Quick change otherwise lgtm

2023-08-09 10:23 UTC, LucasLvy commented on contracts/src/components.cairo
> +impl OutcomePrint of debug::PrintTrait<Option<Outcome>> {
```suggestion
#[cfg(test)]
impl OutcomePrint of debug::PrintTrait<Option<Outcome>> {
```

2023-08-09 10:52 UTC, LucasLvy approved these changes

2023-08-09 10:52 UTC, merged